name: bmsc
description: A new Flutter project.

publish_to: 'none'

version: 99.99.99

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.2.3
  dio: ^5.3.2
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  flutter_html: ^3.0.0-beta.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.0
  audio_session: ^0.1.16
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
