name: bmsc
description: A new Flutter project.

publish_to: 'none'

# this is a placeholder version, it will be replaced by the tag version in the github action
version: 99.99.99
compileSdkVersion: 34

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  just_audio: ^0.9.34
  just_audio_media_kit: ^2.0.6
  media_kit_libs_linux: ^1.1.3
  media_kit_libs_windows_audio: ^1.0.9
  sqflite_common_ffi: ^2.3.4+4
  just_audio_background: ^0.0.1-beta.10
  flutter_html: ^3.0.0-beta.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.0
  audio_session: ^0.1.16
  flutter_launcher_icons: ^0.14.1
  package_info_plus: ^8.1.0
  url_launcher: ^6.1.12
  audio_video_progress_bar: ^2.0.0
  rxdart: ^0.28.0
  sqflite: ^2.3.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.3.0
  logging: ^1.3.0
  crypto: ^3.0.6
  crypton: ^2.2.1
  provider: ^6.1.2
  share_plus: ^10.1.3
  path: ^1.9.1
  file_picker: ^8.1.6
  connectivity_plus: ^6.1.1
  gt3_flutter_plugin:
    git:
      url: https://github.com/u2x1/gt3_flutter_plugin/
      ref: 99cf0cd2b3c224904490c37071c9eec4d7e1782b
  scroll_to_index: ^3.0.1
  async: ^2.12.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"


dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/silent.m4a
    - assets/icon.png
    - changelog.md
  uses-material-design: true
