name: build release apks

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Artifacts and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "17"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: 'stable'
      - run: flutter --version


      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: 'v([0-9]+.[0-9]+.[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Replace YAML version with tag version
        run: |
          sed -i 's/99.99.99/'$GIT_TAG_NAME'/g' pubspec.yaml|
          echo "Tag used version:"$GIT_TAG_NAME
      - name: Pub Get Packages
        run: flutter pub get

      - name: Build apks
        run: flutter build apk --release --split-per-abi

      - name: Extract Changelog
        id: changelog
        run: |
          version="# $(echo ${{ steps.tagName.outputs.tagName }} | sed 's/^v//')"
          changelog=$(awk -v version="$version" '
            $0 ~ version { flag=1; next }
            /^# / && flag { exit }
            flag
          ' changelog.md)
          echo "changelog=$changelog" >> $GITHUB_ENV

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}
          body: ${{ env.changelog }}

      - name: Save apks to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: APKS
          path: build/app/outputs/flutter-apk/*.apk