name: Manual Build (No Tag)

on:
  # 允许在 Actions 页面手动触发此工作流
  workflow_dispatch:
    inputs:
      build_name:
        description: '为本次构建设置一个名称 (例如: dev-build-1)'
        required: true
        default: 'dev-build'
        type: string
      branch:
        description: '请输入要构建的分支'
        required: true
        default: 'main'
        type: string

jobs:
  # JOB 2: Build for iOS (Unsigned)
  build-ios:
    name: Build iOS IPA (Unsigned)
    runs-on: macos-latest
    steps:
      - name: Checkout branch ${{ github.event.inputs.branch }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: 'stable'
      - run: flutter --version

      - name: Replace YAML version with build name
        run: |
          sed -i '' 's/99.99.99/${{ github.event.inputs.build_name }}/g' pubspec.yaml
          echo "build name used version: ${{ github.event.inputs.build_name }}"

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build unsigned iOS App
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos/
          mkdir Payload
          mv Runner.app Payload/
          zip -r ${{ github.event.repository.name }}-${{ github.event.inputs.build_name }}-ios.ipa Payload/
          mv *.ipa ../../../

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.build_name }}-ios-artifact
          path: ${{ github.event.repository.name }}-${{ github.event.inputs.build_name }}-ios.ipa
